const shops = {
  general_stores: [
    "The Adventurer's Outpost",
    "Wanderer's Wares",
    "Provisioner's Haven",
    "The Traveler's Trunk",
    "Wayfarer's Emporium",
    "Nomad's Necessities",
    "Pathfinder's Provisions",
    "Explorer's Essentials",
    "Trailblazer's Trading Post",
    "Vagabond's Vault",
    "Scout's Supply",
    "Forest's Finds",
    "Nomad's Mart",
    "Wayfarer's Warehouse",
    "Pathfinder's Pantry",
    "Drifter's Depot",
    "Voyager's Variety",
    "Explorer's Emporium",
    "Outlander's Outlet",
    "Wayfarer's Waystation",
  ],
  armor_shops: [
    "Knight's Armory",
    "Steel & Shield",
    "Ironbound Emporium",
    "Paladin's Plate",
    "Defender's Depot",
    "Guardian's Gear",
    "Sentinel's Smithy",
    "Armorer's Attire",
    "Forge of Valor",
    "Guardian's Garb",
    "Bastion Bazaar",
    "Templar's Trade",
    "Metal Market",
    "Recruit's Raiment",
    "Warrior's Wardrobe",
    "Iron Shield Armory",
    "Hero's Hideout",
    "Knight's Closet",
    "Guard's Gearhouse",
    "Traitor's Temptation",
  ],
  magic_shops: [
    "Arcane Emporium",
    "Sorcerer's Supply",
    "Wizard's Wonders",
    "Enchanter's Emporium",
    "Mage's Marvels",
    "Mystic Market",
    "Wizardry & Wares",
    "Arcanist's Arsenal",
    "Spellbinder's Shoppe",
    "Enigma Emporium",
    "Thaumaturge's Treasury",
    "Warlock's Wares",
    "Arcane Avenue",
    "Sorcery Source",
    "Wizard's Whims",
    "Mage's Munitions",
    "Spellbound Sanctuary",
    "Conjurer's Closet",
    "Portal's Pantry",
    "Forge of the Magi",
  ],
  weapon_shops: [
    "Blades & Bolts",
    "Mercenary's Mart",
    "Fighter's Forge",
    "Warrior's Workshop",
    "Weaponmaster's Wares",
    "Arms & Armor Emporium",
    "Battleborn Blades",
    "Arms Dealer's Den",
    "Warlord's Weapons",
    "Gladiator's Gear",
    "Swordsmith's Sanctuary",
    "Blade Bazaar",
    "Fighter's Findings",
    "Weapon's Workshop",
    "Mercenary Marketplace",
    "Forge of Fighters",
    "Steel Soldier's Shop",
    "Armsmith's Alley",
    "Warrior's Weaponsmith",
    "Duelist's Depot",
  ],
  alchemist_shops: [
    "Alchemy Emporium",
    "Potion Peddler's",
    "The Apothecary",
    "Herbalist's Haven",
    "Elixir Emporium",
    "Alchemical Adept",
    "Essence Expanse",
    "Potion Pinnacle",
    "Brewmaster's Bounty",
    "Tincture Tavern",
    "Mixer's Market",
    "Potion Palace",
    "Alchemist's Alley",
    "Elixir Emporium",
    "Potion Master's Market",
    "Herbalist Hideout",
    "Essential Elixirs",
    "Brewery Bazaar",
    "Mystic Mixer",
    "Tonic Trade",
  ],
  jewelry_shops: [
    "Gemstone Grotto",
    "Jeweler's Junction",
    "Golden Glade Jewelry",
    "Ornaments & Opals",
    "Treasure Trove Trinkets",
    "Jeweled Jamboree",
    "Gem Guild Gallery",
    "Adornments & Artifacts",
    "Lustrous Luxuries",
    "Precious Metals Parlor",
    "Treasure Trove Trinkets",
    "Jeweled Journey",
    "Gem Gallery",
    "Opulent Ornaments",
    "Golden Grove Gems",
    "Jewelers' Joy",
    "Glimmering Goldsmith",
    "Treasure Trove Treasures",
    "Ornate Oasis",
    "Jeweled Jungle",
  ],
  bookstores: [
    "Tome Traders",
    "Scribe's Sanctuary",
    "Scrolls & Scripts",
    "The Codex Corner",
    "Bookish Bazaar",
    "Literary Lair",
    "Papyrus Pavilion",
    "The Scroll Shelf",
    "Quill & Quire",
    "Scriptorium Square",
    "Bard's Books",
    "Storyteller's Store",
    "Page Turner's Pavilion",
    "Codex Closet",
    "Bookworm's Bazaar",
    "Inkwell Inn",
    "Tome Treasury",
    "Word Weaver's Warehouse",
    "Chapter & Verse",
    "Scroll Seekers",
  ],
  smithies: [
    "Blacksmith's Bounty",
    "Ironworks Inn",
    "Smithy's Sanctuary",
    "Anvil & Forge",
    "Ironbound Inn",
    "Steel & Stone Smithy",
    "Foundry Fellowship",
    "Hammer & Hearth",
    "Metalworks Manor",
    "The Hammer's Handiwork",
    "Steel Stronghold",
    "Ironclad Inn",
    "Smith's Stronghold",
    "Furnace Forge",
    "Blazing Anvil",
    "Forge of the Furnace",
    "Stronghold Smithy",
    "Firebrand Foundry",
    "Metal Master's Manor",
    "Forge of Flame",
  ],
  food_and_drink_shops: [
    "The Hungry Halfling",
    "The Thirsty Troll Tavern",
    "The Frothy Mug",
    "The Roasted Boar",
    "The Sizzling Steakhouse",
    "The Drunken Dragon Inn",
    "The Crusty Croissant Bakery",
    "The Bountiful Barrel Brewery",
    "The Jolly Jester's Jamboree",
    "The Rusty Goblet",
    "The Ravenous Rogue",
    "The Tipsy Tinker Tavern",
    "The Hungry Hero's Hangout",
    "The Blazing Boar Bistro",
    "The Sizzling Sausage Stand",
    "The Frothy Fae Fete",
    "The Gilded Goblet",
    "The Drunken Dwarf Distillery",
    "The Salty Sailor's Saloon",
    "The Thirsty Thrasher's Tavern",
  ],
  clothing_stores: [
    "Weaver's Wardrobe",
    "Tailor's Treasure Trove",
    "Fabric & Finery",
    "The Silken Sash",
    "Thread & Needle Textiles",
    "The Fashionable Frock",
    "The Velvet Vestment",
    "The Elegant Ensemble",
    "The Stylish Stich",
    "The Couture Collection",
    "The Sewing Sanctuary",
    "The Dapper Dresser",
    "The Stylist's Studio",
    "The Trendy Tailor",
    "The Sophisticated Seamstress",
    "The Clothier's Closet",
    "The Fashion Forge",
    "The Chic Clothier",
    "The Glamorous Garb",
    "The Elegant Emporium",
    "The Fancy Fabric Shop",
    "The Couture Corner",
    "The Tailor's Temptation",
    "The Stitched Style Shop",
    "The Fashionista's Find",
  ],
  clothing_stores: {
    items: [
      {
        name: "Simple Shirt",
        price: "2 sp",
        rarity: "common",
      },
      {
        name: "Trousers",
        price: "2 sp",
        rarity: "common",
      },
      {
        name: "Simple Dress",
        price: "2 sp",
        rarity: "common",
      },
      {
        name: "Cloak",
        price: "1 gp",
        rarity: "common",
      },
      {
        name: "Boots",
        price: "2 sp",
        rarity: "common",
      },
      {
        name: "Hat",
        price: "5 sp",
        rarity: "common",
      },
      {
        name: "Gloves",
        price: "5 sp",
        rarity: "common",
      },
      {
        name: "Belt",
        price: "1 sp",
        rarity: "common",
      },
      {
        name: "Vest",
        price: "3 sp",
        rarity: "common",
      },
      {
        name: "Skirt",
        price: "2 sp",
        rarity: "common",
      },
      {
        name: "Jacket",
        price: "2 gp",
        rarity: "common",
      },
      {
        name: "Dress Shoes",
        price: "3 gp",
        rarity: "common",
      },
      {
        name: "Formal Gown",
        price: "5 gp",
        rarity: "uncommon",
      },
      {
        name: "Fancy Hat",
        price: "3 gp",
        rarity: "uncommon",
      },
      {
        name: "Silk Scarf",
        price: "2 gp",
        rarity: "uncommon",
      },
      {
        name: "Leather Jacket",
        price: "4 gp",
        rarity: "uncommon",
      },
      {
        name: "Fur-lined Cloak",
        price: "5 gp",
        rarity: "uncommon",
      },
      {
        name: "Embroidered Gloves",
        price: "4 gp",
        rarity: "uncommon",
      },
      {
        name: "Silver Buckle Belt",
        price: "3 gp",
        rarity: "uncommon",
      },
      {
        name: "Chainmail Vest",
        price: "10 gp",
        rarity: "rare",
      },
    ],
  },
};
