export const randomNames = {
  human: {
    description:
      "Humans are versatile and ambitious, often striving for greatness in diverse fields. They are known for their adaptability, resilience, and determination.",
    first_names: {
      male: [
        "Alaric",
        "Benedict",
        "Cedric",
        "Darian",
        "Edmund",
        "Gareth",
        "Hugo",
        "Julian",
        "Leon",
        "Miles",
        "Nathaniel",
        "Oliver",
        "Percival",
        "Quentin",
        "Roland",
        "Sebastian",
        "Tristan",
        "Ulric",
        "Victor",
        "Wesley",
      ],
      female: [
        "Ariana",
        "Bianca",
        "Cassandra",
        "Diana",
        "Elena",
        "Fiona",
        "Gabriella",
        "Helena",
        "Isabella",
        "Juliet",
        "Katherine",
        "Lydia",
        "Morgana",
        "Nadia",
        "Ophelia",
        "Penelope",
        "Rosalind",
        "Seraphina",
        "Talia",
        "Victoria",
      ],
    },
    last_names: [
      "Hawthorne",
      "Blackwood",
      "Whitmore",
      "Frost",
      "Wilder",
      "Stormwind",
      "Ravencrest",
      "Nightingale",
      "Brightblade",
      "Strongbow",
      "Ironheart",
      "Winterborne",
      "Thornfield",
      "Stormrider",
      "Sunstrider",
      "Frostbane",
      "Ravenwood",
      "Silverhand",
      "Brightshield",
      "Grimwald",
    ],
    descriptions: {
      male: [
        "A tall, muscular man with piercing blue eyes and dark hair. He has a commanding presence and often wears a stern expression.",
        "A lean, sharp-featured individual with short black hair and intense green eyes. He is always impeccably dressed.",
        "A stout man with a broad chest and a friendly demeanor. He has sandy blonde hair and a warm smile.",
        "A tall and slender man with silver hair and pale skin. His ice-blue eyes give him an enigmatic look.",
        "A rugged man with a weather-beaten face and dark brown hair. His hazel eyes reflect his adventurous spirit.",
        "A broad-shouldered warrior with a mane of dark hair and a trimmed beard. His deep brown eyes are full of determination.",
        "A tall, slender man with long black hair tied back in a ponytail. His grey eyes are observant and piercing.",
        "A charming man with curly brown hair and sparkling blue eyes. His smile is disarming and friendly.",
        "A well-built knight with short-cropped blonde hair and steel-grey eyes. His posture is always upright and confident.",
        "A lanky archer with auburn hair and keen green eyes. He moves with a quiet grace and agility.",
        "A burly blacksmith with a powerful build and dark, curly hair. His brown eyes are steady and reliable.",
        "A slim, intellectual man with neat blonde hair and blue eyes. He often wears glasses and carries a book.",
        "A nobleman with sharp features, dark hair, and piercing grey eyes. He has an air of authority and elegance.",
        "A daring adventurer with wild brown hair and bright hazel eyes. His grin is infectious and bold.",
        "A seasoned warrior with a grizzled beard and numerous scars. His steely eyes show years of battle experience.",
        "A charismatic man with dark, wavy hair and a roguish smile. His blue eyes are full of mischief.",
        "A serious, disciplined man with short brown hair and intense, focused eyes. His presence is commanding.",
        "A tall, rugged man with a thick beard and piercing blue eyes. His voice is deep and resonant.",
        "A knight in shining armor with a noble bearing and golden hair. His bright eyes inspire confidence and trust.",
        "A quiet, introspective man with dark hair and soft brown eyes. He often seems lost in thought.",
      ],
      female: [
        "A tall, graceful woman with long, flowing blonde hair and bright blue eyes. She moves with elegance and poise.",
        "A fierce warrior with short black hair and piercing green eyes. Her presence is commanding and formidable.",
        "A kind-hearted healer with auburn hair and warm brown eyes. Her smile is gentle and reassuring.",
        "A regal woman with striking features and deep blue eyes. Her dark hair cascades in waves down her back.",
        "A charming and witty lady with short, curly brown hair and twinkling hazel eyes. She is always ready with a clever remark.",
        "A mysterious sorceress with long, silver hair and piercing violet eyes. Her aura is both enchanting and intimidating.",
        "A scholarly woman with neat brown hair and glasses. Her green eyes are always alight with curiosity and intelligence.",
        "A brave adventurer with fiery red hair and a fierce expression. Her blue eyes are full of determination.",
        "A noblewoman with elegant features and a soft, melodic voice. Her blonde hair is always impeccably styled.",
        "A talented bard with long, dark hair and sparkling green eyes. Her laughter is infectious and her songs are captivating.",
        "A strong and determined warrior with short, spiky blonde hair and intense blue eyes. She carries herself with confidence.",
        "A graceful dancer with long, flowing red hair and enchanting green eyes. Her movements are fluid and mesmerizing.",
        "A wise and experienced mage with silver-streaked hair and deep brown eyes. Her presence commands respect and admiration.",
        "A skilled archer with short, tousled brown hair and sharp blue eyes. She moves with agility and precision.",
        "A gentle and compassionate healer with long, golden hair and warm brown eyes. Her touch is soothing and kind.",
        "A fearless pirate with wild black hair and piercing grey eyes. Her demeanor is bold and daring.",
        "A beautiful and mysterious woman with long, dark hair and deep, soulful eyes. Her smile is both alluring and enigmatic.",
        "A cheerful and energetic young woman with short, curly red hair and bright blue eyes. Her enthusiasm is contagious.",
        "A fierce and determined warrior with long, flowing blonde hair and intense green eyes. Her presence is commanding.",
        "A wise and serene woman with silver hair and calm, blue eyes. She radiates peace and wisdom.",
      ],
    },
  },
  elf: {
    description:
      "Elves are known for their grace, longevity, and connection to nature. They possess a natural affinity for magic and are often seen as wise and mysterious.",
    first_names: {
      male: [
        "Aelar",
        "Eldrin",
        "Faelar",
        "Ilian",
        "Laucian",
        "Peren",
        "Riardon",
        "Theren",
        "Varis",
        "Zaos",
        "Adran",
        "Arannis",
        "Berrian",
        "Carric",
        "Enialis",
        "Galinndan",
        "Himo",
        "Ivellios",
        "Liamin",
        "Mythanar",
      ],
      female: [
        "Aelina",
        "Elaria",
        "Fayeth",
        "Liora",
        "Myriani",
        "Naivara",
        "Sarith",
        "Thalia",
        "Valanthe",
        "Xanaphia",
        "Althaea",
        "Anastrianna",
        "Caelynn",
        "Drusilia",
        "Enna",
        "Felosial",
        "Ielenia",
        "Keyleth",
        "Leshanna",
        "Meriele",
      ],
    },
    last_names: [
      "Moonshadow",
      "Stargazer",
      "Windrunner",
      "Nightwhisper",
      "Swiftblade",
      "Lightfoot",
      "Silverleaf",
      "Starshine",
      "Mistwalker",
      "Moonblade",
      "Starfall",
      "Duskrunner",
      "Silverbreeze",
      "Everbloom",
      "Sunfire",
      "Moonwhisper",
      "Lightbringer",
      "Nightbreeze",
      "Eveningfall",
      "Starweaver",
    ],
    descriptions: {
      male: [
        "A tall, slender elf with long silver hair and piercing blue eyes. His movements are graceful and fluid.",
        "A sharp-featured elf with short, dark hair and intense green eyes. He carries himself with an air of authority.",
        "A lithe and agile elf with golden hair and bright green eyes. His smile is charming and infectious.",
        "A mysterious elf with long, flowing black hair and deep, soulful eyes. He often seems lost in thought.",
        "A strong and noble elf with shoulder-length brown hair and sharp, grey eyes. He exudes confidence and wisdom.",
        "A youthful elf with tousled blonde hair and twinkling blue eyes. His energy is boundless and infectious.",
        "A wise and experienced elf with silver-streaked hair and calm, blue eyes. He moves with deliberate precision.",
        "A quiet and introspective elf with short, dark hair and piercing green eyes. He speaks little but observes much.",
        "A cheerful and friendly elf with curly brown hair and warm, hazel eyes. His laugh is infectious and warm.",
        "A brooding elf with long, dark hair and sharp, green eyes. His presence is both captivating and intimidating.",
        "A regal elf with long, flowing blonde hair and piercing blue eyes. He carries himself with an air of nobility.",
        "A quick-witted elf with short, spiky black hair and bright, inquisitive eyes. He is always curious and eager to learn.",
        "A gentle and kind-hearted elf with long, wavy brown hair and soft, green eyes. His smile is warm and reassuring.",
        "A daring and adventurous elf with wild, untamed hair and bright, keen eyes. He is always ready for a new challenge.",
        "A calm and serene elf with short, neat hair and deep, thoughtful eyes. He moves with a quiet grace and dignity.",
        "A fierce and determined elf with short-cropped blonde hair and intense, focused eyes. He is a warrior through and through.",
        "A charismatic elf with long, flowing black hair and a roguish smile. His eyes sparkle with mischief and charm.",
        "A wise and venerable elf with silver hair and calm, serene eyes. He exudes an air of peace and tranquility.",
        "A strong and stoic elf with dark hair and piercing blue eyes. He is a natural leader and commands respect.",
        "A cheerful and optimistic elf with short, curly hair and bright, twinkling eyes. His positivity is contagious.",
      ],
      female: [
        "A tall, elegant elf with long, golden hair and sparkling blue eyes. She moves with grace and poise.",
        "A fierce warrior with short, fiery red hair and piercing green eyes. Her presence is commanding and formidable.",
        "A kind-hearted healer with long, silver hair and warm, brown eyes. Her touch is gentle and soothing.",
        "A regal elf with striking features and deep, violet eyes. Her dark hair flows like a river of midnight.",
        "A mysterious sorceress with long, black hair and glowing, amber eyes. She is both enchanting and intimidating.",
        "A scholarly elf with neat, brown hair and intelligent, green eyes. She is always curious and eager to learn.",
        "A brave adventurer with short, spiky blonde hair and fierce, blue eyes. Her determination is unshakable.",
        "A noblewoman with elegant features and a soft, melodic voice. Her long hair cascades in waves down her back.",
        "A talented bard with long, dark hair and bright, green eyes. Her songs are captivating and full of life.",
        "A strong and determined warrior with short, spiky black hair and intense, blue eyes. She is confident and fearless.",
        "A graceful dancer with long, flowing red hair and enchanting green eyes. Her movements are mesmerizing.",
        "A wise and experienced mage with silver-streaked hair and deep, brown eyes. She commands respect and admiration.",
        "A skilled archer with short, tousled brown hair and sharp, blue eyes. She moves with precision and agility.",
        "A gentle and compassionate healer with long, golden hair and warm, brown eyes. Her presence is soothing.",
        "A fearless pirate with wild, black hair and piercing, grey eyes. Her demeanor is bold and daring.",
        "A beautiful and mysterious elf with long, dark hair and deep, soulful eyes. Her smile is both alluring and enigmatic.",
        "A cheerful and energetic young elf with short, curly red hair and bright, blue eyes. Her enthusiasm is contagious.",
        "A fierce and determined warrior with long, flowing blonde hair and intense, green eyes. Her presence is commanding.",
        "A wise and serene elf with silver hair and calm, blue eyes. She radiates peace and wisdom.",
        "A quiet and introspective elf with short, dark hair and piercing green eyes. She is observant and thoughtful.",
      ],
    },
  },
  dwarf: {
    description:
      "Dwarves are known for their stout and sturdy build, their affinity for mining and metalwork, and their resilience and loyalty. They are often seen as strong, reliable, and skilled craftsmen.",
    first_names: {
      male: [
        "Baern",
        "Barendd",
        "Brottor",
        "Dain",
        "Eberk",
        "Einkil",
        "Fargrim",
        "Garik",
        "Harbek",
        "Kildrak",
        "Morgran",
        "Orsik",
        "Rurik",
        "Taklinn",
        "Thoradin",
        "Traubon",
        "Tordek",
        "Ulfgar",
        "Veit",
        "Vondal",
      ],
      female: [
        "Amber",
        "Artin",
        "Audhild",
        "Bardryn",
        "Dagnal",
        "Diesa",
        "Eldeth",
        "Falkrunn",
        "Finellen",
        "Gunnloda",
        "Gurdis",
        "Helja",
        "Hlin",
        "Kathra",
        "Kristryd",
        "Ilde",
        "Liftrasa",
        "Sannl",
        "Torbera",
        "Vistra",
      ],
    },
    last_names: [
      "Balderk",
      "Battlehammer",
      "Brawnanvil",
      "Dankil",
      "Fireforge",
      "Frostbeard",
      "Gorunn",
      "Holderhek",
      "Ironfist",
      "Loderr",
      "Lutgehr",
      "Rumnaheim",
      "Strakeln",
      "Torunn",
      "Ungart",
      "Granitepeak",
      "Strongarm",
      "Stonehelm",
      "Ironfoot",
      "Bronzeaxe",
    ],
    descriptions: {
      male: [
        "A burly dwarf with a thick, braided beard and piercing blue eyes. His arms are muscular from years of blacksmithing.",
        "A stout dwarf with a bald head and a long, flowing brown beard. His deep voice commands attention.",
        "A rugged dwarf with a bushy red beard and bright green eyes. He is always ready for a fight.",
        "A sturdy dwarf with a thick, black beard and intense, grey eyes. His presence is imposing and solid.",
        "A wise dwarf with a neatly trimmed grey beard and wise, brown eyes. His movements are deliberate and thoughtful.",
        "A strong dwarf with a wild, unkempt beard and sharp, blue eyes. He is always full of energy and enthusiasm.",
        "A grim dwarf with a long, dark beard and piercing black eyes. He has a serious demeanor and a strong sense of duty.",
        "A jovial dwarf with a short, blonde beard and twinkling blue eyes. His laughter is hearty and contagious.",
        "A fierce dwarf with a braided white beard and steely grey eyes. He is a seasoned warrior with numerous scars.",
        "A friendly dwarf with a bushy brown beard and warm, hazel eyes. He is always ready to lend a helping hand.",
        "A noble dwarf with a meticulously groomed black beard and sharp, green eyes. His posture is always upright and proud.",
        "A battle-hardened dwarf with a thick, red beard and intense, blue eyes. His presence is both intimidating and commanding.",
        "A cheerful dwarf with a short, grey beard and bright, blue eyes. He is always full of stories and jokes.",
        "A stoic dwarf with a long, black beard and piercing, brown eyes. He is quiet but incredibly reliable.",
        "A determined dwarf with a wild, red beard and sharp, blue eyes. His resolve is unbreakable.",
        "A wise and experienced dwarf with a neatly trimmed grey beard and calm, green eyes. He exudes confidence and wisdom.",
        "A rugged dwarf with a thick, brown beard and intense, blue eyes. He is always ready for an adventure.",
        "A kind-hearted dwarf with a short, blonde beard and warm, brown eyes. His smile is always reassuring.",
        "A fierce dwarf with a long, black beard and piercing, grey eyes. He is a warrior through and through.",
        "A friendly dwarf with a bushy, red beard and twinkling, green eyes. His laugh is hearty and infectious.",
      ],
      female: [
        "A strong, stocky dwarf with long, braided brown hair and piercing blue eyes. She is known for her incredible strength.",
        "A fierce warrior with short, spiky black hair and intense green eyes. Her presence is commanding and formidable.",
        "A kind-hearted healer with long, flowing red hair and warm, brown eyes. Her touch is gentle and soothing.",
        "A regal dwarf with striking features and deep, violet eyes. Her dark hair flows like a river of midnight.",
        "A mysterious sorceress with long, black hair and glowing, amber eyes. She is both enchanting and intimidating.",
        "A scholarly dwarf with neat, brown hair and intelligent, green eyes. She is always curious and eager to learn.",
        "A brave adventurer with short, spiky blonde hair and fierce, blue eyes. Her determination is unshakable.",
        "A noblewoman with elegant features and a soft, melodic voice. Her long hair cascades in waves down her back.",
        "A talented bard with long, dark hair and bright, green eyes. Her songs are captivating and full of life.",
        "A strong and determined warrior with short, spiky black hair and intense, blue eyes. She is confident and fearless.",
        "A graceful dancer with long, flowing red hair and enchanting green eyes. Her movements are mesmerizing.",
        "A wise and experienced mage with silver-streaked hair and deep, brown eyes. She commands respect and admiration.",
        "A skilled archer with short, tousled brown hair and sharp, blue eyes. She moves with precision and agility.",
        "A gentle and compassionate healer with long, golden hair and warm, brown eyes. Her presence is soothing.",
        "A fearless pirate with wild, black hair and piercing, grey eyes. Her demeanor is bold and daring.",
        "A beautiful and mysterious dwarf with long, dark hair and deep, soulful eyes. Her smile is both alluring and enigmatic.",
        "A cheerful and energetic young dwarf with short, curly red hair and bright, blue eyes. Her enthusiasm is contagious.",
        "A fierce and determined warrior with long, flowing blonde hair and intense, green eyes. Her presence is commanding.",
        "A wise and serene dwarf with silver hair and calm, blue eyes. She radiates peace and wisdom.",
        "A quiet and introspective dwarf with short, dark hair and piercing green eyes. She is observant and thoughtful.",
      ],
    },
  },
  halfling: {
    description:
      "Halflings are known for their small stature, cheerful demeanor, and nimble agility. They value home, family, and simple pleasures, often seen as friendly and optimistic.",
    first_names: {
      male: [
        "Alton",
        "Ander",
        "Cade",
        "Corrin",
        "Eldon",
        "Errich",
        "Finnan",
        "Garret",
        "Lindal",
        "Lyle",
        "Merric",
        "Milo",
        "Osborn",
        "Perrin",
        "Reed",
        "Roscoe",
        "Wellby",
        "Tye",
        "Jasper",
        "Quinn",
      ],
      female: [
        "Andry",
        "Bree",
        "Callie",
        "Cora",
        "Euphemia",
        "Jillian",
        "Kithri",
        "Lavina",
        "Lidda",
        "Merla",
        "Nedda",
        "Paela",
        "Portia",
        "Seraphina",
        "Shaena",
        "Trym",
        "Vani",
        "Verna",
        "Brynna",
        "Piper",
      ],
    },
    last_names: [
      "Brushgather",
      "Goodbarrel",
      "Greenbottle",
      "High-hill",
      "Hilltopple",
      "Leagallow",
      "Tealeaf",
      "Thorngage",
      "Tosscobble",
      "Underbough",
      "Warmwater",
      "Proudfoot",
      "Lightfoot",
      "Appleblossom",
      "Deepdelver",
      "Elderberry",
      "Shadowquick",
      "Frostwhisper",
      "Sunmeadow",
      "Quickstep",
    ],
    descriptions: {
      male: [
        "A small, nimble halfling with curly brown hair and bright green eyes. He is always cheerful and full of energy.",
        "A stout halfling with a round face and a mischievous grin. His short black hair is always a bit tousled.",
        "A lean halfling with sharp features and quick, blue eyes. He moves with incredible agility and speed.",
        "A friendly halfling with sandy blonde hair and twinkling hazel eyes. His laugh is infectious and hearty.",
        "A quiet halfling with dark, straight hair and piercing blue eyes. He often seems deep in thought.",
        "A cheerful halfling with curly red hair and bright green eyes. His smile can light up any room.",
        "A sturdy halfling with short brown hair and a broad, friendly face. His presence is comforting and reliable.",
        "A jovial halfling with a round belly and a hearty laugh. His dark hair is always neatly combed.",
        "A clever halfling with quick, intelligent eyes and a perpetual grin. His dark hair is always slightly messy.",
        "A young, energetic halfling with short blonde hair and bright blue eyes. His enthusiasm is contagious.",
        "A wise halfling with graying hair and kind, brown eyes. He moves with a calm and deliberate grace.",
        "A strong halfling with a muscular build and a determined expression. His dark eyes are full of resolve.",
        "A curious halfling with sandy brown hair and wide, inquisitive eyes. He is always eager to learn something new.",
        "A carefree halfling with curly blonde hair and a sunny disposition. His laugh is loud and full of joy.",
        "A stealthy halfling with dark hair and quick, darting eyes. He moves with the silent grace of a shadow.",
        "A charming halfling with wavy brown hair and a warm smile. His blue eyes are always full of kindness.",
        "A brave halfling with short, spiky hair and fierce, determined eyes. He is always ready for an adventure.",
        "A calm halfling with straight black hair and serene, green eyes. His presence is soothing and peaceful.",
        "A friendly halfling with a wide smile and twinkling eyes. His short brown hair is always perfectly styled.",
        "A mischievous halfling with a twinkle in his eye and a knack for finding trouble. His quick wit keeps him out of most of it.",
      ],
      female: [
        "A small, graceful halfling with long, flowing blonde hair and bright blue eyes. She moves with elegance and poise.",
        "A cheerful halfling with curly red hair and sparkling green eyes. Her laughter is infectious and full of joy.",
        "A kind-hearted halfling with long, dark hair and warm brown eyes. Her touch is gentle and soothing.",
        "A nimble halfling with short, wavy hair and sharp, green eyes. She is always quick on her feet.",
        "A wise halfling with silver-streaked hair and calm, blue eyes. She exudes an air of tranquility and wisdom.",
        "A fierce halfling with short, spiky black hair and intense, brown eyes. Her presence is commanding and strong.",
        "A friendly halfling with curly brown hair and a warm smile. Her hazel eyes are always twinkling with kindness.",
        "A brave halfling with long, flowing red hair and bright blue eyes. She is always ready for an adventure.",
        "A graceful halfling with long, dark hair and deep green eyes. Her movements are fluid and enchanting.",
        "A talented halfling with short blonde hair and a beautiful singing voice. Her songs are captivating and full of emotion.",
        "A gentle halfling with short, straight hair and soft, brown eyes. Her presence is calming and reassuring.",
        "A mischievous halfling with short, curly hair and bright, green eyes. She always has a clever remark ready.",
        "A calm halfling with long, wavy hair and serene, blue eyes. Her presence is peaceful and comforting.",
        "A determined halfling with short, spiky hair and fierce, green eyes. She is always ready to stand up for what she believes in.",
        "A kind-hearted halfling with long, flowing brown hair and warm, hazel eyes. Her smile is gentle and reassuring.",
        "A curious halfling with short, straight hair and wide, blue eyes. She is always eager to learn something new.",
        "A charming halfling with wavy red hair and a bright, sunny smile. Her laughter is infectious and full of life.",
        "A stealthy halfling with dark hair and quick, darting eyes. She moves with the silent grace of a shadow.",
        "A cheerful halfling with long, curly hair and twinkling green eyes. Her positivity is contagious.",
        "A fierce halfling with short, straight hair and intense, brown eyes. She is a warrior through and through.",
      ],
    },
  },
  dragonborn: {
    description:
      "Dragonborn are proud and noble creatures with draconic ancestry. They are known for their strength, honor, and fierce loyalty.",
    first_names: {
      male: [
        "Arjhan",
        "Balasar",
        "Bharash",
        "Donaar",
        "Ghesh",
        "Heskan",
        "Kriv",
        "Medrash",
        "Mehen",
        "Nadarr",
        "Pandjed",
        "Patrin",
        "Rhogar",
        "Shamash",
        "Shedinn",
        "Tarhun",
        "Torinn",
        "Amon",
        "Bahram",
        "Dorn",
      ],
      female: [
        "Akra",
        "Biri",
        "Daar",
        "Farideh",
        "Harann",
        "Havilar",
        "Jheri",
        "Kriv",
        "Mishann",
        "Nala",
        "Perra",
        "Raiann",
        "Sora",
        "Surina",
        "Thava",
        "Uadjit",
        "Vezera",
        "Westra",
        "Zara",
        "Zofya",
      ],
    },
    last_names: [
      "Clethtinthiallor",
      "Daardendrian",
      "Delmirev",
      "Drachedandion",
      "Fenkenkabradon",
      "Kepeshkmolik",
      "Kerrhylon",
      "Kimbatuul",
      "Linxakasendalor",
      "Myastan",
      "Nemmonis",
      "Norixius",
      "Ophinshtalajiir",
      "Prexijandilin",
      "Shestendeliath",
      "Turnuroth",
      "Verthisathurgiesh",
      "Yarjerit",
    ],
    descriptions: {
      male: [
        "A towering dragonborn with deep red scales and piercing yellow eyes. His presence commands respect and awe.",
        "A noble dragonborn with sleek, silver scales and wise, blue eyes. His movements are graceful and deliberate.",
        "A fierce dragonborn with dark black scales and glowing red eyes. His roar sends shivers down the spine of his enemies.",
        "A regal dragonborn with shimmering bronze scales and piercing green eyes. His voice carries the weight of authority.",
        "A powerful dragonborn with golden scales and intense, amber eyes. His strength is unmatched on the battlefield.",
        "A stoic dragonborn with emerald green scales and deep, thoughtful eyes. His wisdom is sought after by many.",
        "A proud dragonborn with azure blue scales and piercing, steel-grey eyes. His loyalty is unwavering.",
        "A cunning dragonborn with midnight black scales and sharp, yellow eyes. His intellect is as sharp as his claws.",
        "A battle-hardened dragonborn with scarred scales and fierce, crimson eyes. His courage is unmatched.",
        "A fearsome dragonborn with obsidian scales and glowing, orange eyes. His presence instills fear in his enemies.",
        "A wise dragonborn with iridescent scales and calm, violet eyes. His knowledge of ancient lore is unparalleled.",
        "A majestic dragonborn with vibrant gold scales and piercing, sapphire eyes. His charisma is undeniable.",
        "A stalwart dragonborn with steel-grey scales and keen, silver eyes. His determination is unyielding.",
        "A fierce dragonborn with crimson scales and blazing, ruby eyes. His rage is a force to be reckoned with.",
        "A noble dragonborn with shimmering platinum scales and wise, amber eyes. His leadership inspires greatness in others.",
        "A powerful dragonborn with jade green scales and piercing, emerald eyes. His strength is matched only by his honor.",
        "A cunning dragonborn with onyx black scales and sharp, silver eyes. His wit is as sharp as his blade.",
        "A battle-scarred dragonborn with burnished bronze scales and fierce, cobalt eyes. His courage is legendary.",
        "A fearsome dragonborn with obsidian scales and glowing, crimson eyes. His presence strikes fear into the hearts of his enemies.",
        "A wise dragonborn with shimmering pearl scales and calm, azure eyes. His knowledge of magic is unrivaled.",
      ],
      female: [
        "A majestic dragonborn with vibrant gold scales and piercing, sapphire eyes. Her charisma is undeniable.",
        "A stalwart dragonborn with steel-grey scales and keen, silver eyes. Her determination is unyielding.",
        "A fierce dragonborn with crimson scales and blazing, ruby eyes. Her rage is a force to be reckoned with.",
        "A noble dragonborn with shimmering platinum scales and wise, amber eyes. Her leadership inspires greatness in others.",
        "A powerful dragonborn with jade green scales and piercing, emerald eyes. Her strength is matched only by her honor.",
        "A cunning dragonborn with onyx black scales and sharp, silver eyes. Her wit is as sharp as her blade.",
        "A battle-scarred dragonborn with burnished bronze scales and fierce, cobalt eyes. Her courage is legendary.",
        "A fearsome dragonborn with obsidian scales and glowing, crimson eyes. Her presence strikes fear into the hearts of her enemies.",
        "A wise dragonborn with shimmering pearl scales and calm, azure eyes. Her knowledge of magic is unrivaled.",
        "A towering dragonborn with deep red scales and piercing yellow eyes. Her presence commands respect and awe.",
        "A noble dragonborn with sleek, silver scales and wise, blue eyes. Her movements are graceful and deliberate.",
        "A fierce dragonborn with dark black scales and glowing red eyes. Her roar sends shivers down the spine of her enemies.",
        "A regal dragonborn with shimmering bronze scales and piercing green eyes. Her voice carries the weight of authority.",
        "A powerful dragonborn with golden scales and intense, amber eyes. Her strength is unmatched on the battlefield.",
        "A stoic dragonborn with emerald green scales and deep, thoughtful eyes. Her wisdom is sought after by many.",
        "A proud dragonborn with azure blue scales and piercing, steel-grey eyes. Her loyalty is unwavering.",
        "A cunning dragonborn with midnight black scales and sharp, yellow eyes. Her intellect is as sharp as her claws.",
        "A battle-hardened dragonborn with scarred scales and fierce, crimson eyes. Her courage is unmatched.",
        "A fearsome dragonborn with obsidian scales and glowing, orange eyes. Her presence instills fear in her enemies.",
        "A wise dragonborn with iridescent scales and calm, violet eyes. Her knowledge of ancient lore is unparalleled.",
      ],
    },
  },
  gnome: {
    description:
      "Gnomes are small, inventive creatures known for their curiosity, intelligence, and boundless energy. They are skilled craftsmen, engineers, and tinkerers, often creating intricate gadgets and devices to solve problems and entertain themselves.",
    first_names: {
      male: [
        "Alston",
        "Boddynock",
        "Brocc",
        "Burgell",
        "Dimble",
        "Eldon",
        "Erky",
        "Fonkin",
        "Frug",
        "Gerbo",
        "Gimble",
        "Glim",
        "Jebeddo",
        "Kellen",
        "Namfoodle",
        "Orryn",
        "Roondar",
        "Seebo",
        "Sindri",
        "Warryn",
      ],
      female: [
        "Bimpnottin",
        "Breena",
        "Caramip",
        "Carlin",
        "Donella",
        "Duvamil",
        "Ella",
        "Ellyjobell",
        "Ellywick",
        "Lilli",
        "Loopmottin",
        "Lorilla",
        "Mardnab",
        "Nissa",
        "Nyx",
        "Oda",
        "Orla",
        "Roywyn",
        "Shamil",
        "Tana",
      ],
    },
    last_names: [
      "Beren",
      "Droukdel",
      "Folkor",
      "Garrick",
      "Nackle",
      "Murnig",
      "Nackle",
      "Ningel",
      "Raulnor",
      "Scheppen",
      "Turen",
      "Nackle",
      "Lorilla",
      "Murnig",
      "Turen",
      "Nackle",
      "Ningel",
      "Raulnor",
      "Scheppen",
      "Turen",
    ],
    descriptions: {
      male: [
        "A gnome with a mischievous grin and a twinkle in his eye. His pockets are always full of curious gadgets and trinkets.",
        "A gnome with wild hair and a perpetual look of wonder on his face. His mind is constantly buzzing with ideas and inventions.",
        "A gnome with glasses perched on his nose and a book always at hand. His thirst for knowledge and love for tinkering know no bounds.",
        "A gnome with a serious expression and a keen eye for detail. His craftsmanship is impeccable, and his inventions are marvels of engineering.",
        "A gnome with a quick wit and a sharp tongue. His jokes and pranks keep his friends entertained and his enemies on their toes.",
        "A gnome with a gentle demeanor and a kind heart. His compassion and empathy make him a beloved figure in his community.",
        "A gnome with a fierce determination and a steely resolve. His dedication to his craft and his friends is unwavering.",
        "A gnome with a playful nature and a love for adventure. His curiosity often gets him into trouble, but his ingenuity always gets him out.",
        "A gnome with a keen intellect and a thirst for knowledge. His experiments and inventions push the boundaries of what is possible.",
        "A gnome with a quick temper and a fiery spirit. His passion for his work and his friends is matched only by his love for a good prank.",
        "A gnome with a quiet demeanor and a sharp mind. His insights and observations are often overlooked, but they hold the key to solving many problems.",
        "A gnome with a love for music and a talent for tinkering. His inventions are as beautiful as they are functional.",
        "A gnome with a love for animals and a knack for communication. His ability to speak with creatures of all kinds makes him a valuable ally in the wild.",
        "A gnome with a love for stories and a gift for storytelling. His tales of adventure and magic captivate audiences of all ages.",
        "A gnome with a love for the sea and a thirst for adventure. His tales of sailing the high seas and battling sea monsters are legendary.",
        "A gnome with a love for the stars and a passion for exploration. His dreams of traveling to distant worlds and uncovering the secrets of the universe inspire all who know him.",
        "A gnome with a love for nature and a deep connection to the earth. His knowledge of plants and animals is unmatched, and his respect for the natural world is unwavering.",
        "A gnome with a love for art and a talent for painting. His works are colorful and vibrant, capturing the beauty of the world around him.",
        "A gnome with a love for food and a talent for cooking. His recipes are legendary, and his meals are the highlight of any gathering.",
        "A gnome with a love for puzzles and a knack for solving them. His mind is like a finely tuned machine, always working to unravel the mysteries of the world.",
        "A gnome with a love for magic and a talent for illusion. His tricks and spells dazzle and delight, leaving audiences spellbound and wanting more.",
      ],
      female: [
        "A gnome with a mischievous grin and a twinkle in her eye. Her pockets are always full of curious gadgets and trinkets.",
        "A gnome with wild hair and a perpetual look of wonder on her face. Her mind is constantly buzzing with ideas and inventions.",
        "A gnome with glasses perched on her nose and a book always at hand. Her thirst for knowledge and love for tinkering know no bounds.",
        "A gnome with a serious expression and a keen eye for detail. Her craftsmanship is impeccable, and her inventions are marvels of engineering.",
        "A gnome with a quick wit and a sharp tongue. Her jokes and pranks keep her friends entertained and her enemies on their toes.",
        "A gnome with a gentle demeanor and a kind heart. Her compassion and empathy make her a beloved figure in her community.",
        "A gnome with a fierce determination and a steely resolve. Her dedication to her craft and her friends is unwavering.",
        "A gnome with a playful nature and a love for adventure. Her curiosity often gets her into trouble, but her ingenuity always gets her out.",
        "A gnome with a keen intellect and a thirst for knowledge. Her experiments and inventions push the boundaries of what is possible.",
        "A gnome with a quick temper and a fiery spirit. Her passion for her work and her friends is matched only by her love for a good prank.",
        "A gnome with a quiet demeanor and a sharp mind. Her insights and observations are often overlooked, but they hold the key to solving many problems.",
        "A gnome with a love for music and a talent for tinkering. Her inventions are as beautiful as they are functional.",
        "A gnome with a love for animals and a knack for communication. Her ability to speak with creatures of all kinds makes her a valuable ally in the wild.",
        "A gnome with a love for stories and a gift for storytelling. Her tales of adventure and magic captivate audiences of all ages.",
        "A gnome with a love for the sea and a thirst for adventure. Her tales of sailing the high seas and battling sea monsters are legendary.",
        "A gnome with a love for the stars and a passion for exploration. Her dreams of traveling to distant worlds and uncovering the secrets of the universe inspire all who know her.",
        "A gnome with a love for nature and a deep connection to the earth. Her knowledge of plants and animals is unmatched, and her respect for the natural world is unwavering.",
        "A gnome with a love for art and a talent for painting. Her works are colorful and vibrant, capturing the beauty of the world around her.",
        "A gnome with a love for food and a talent for cooking. Her recipes are legendary, and her meals are the highlight of any gathering.",
        "A gnome with a love for puzzles and a knack for solving them. Her mind is like a finely tuned machine, always working to unravel the mysteries of the world.",
        "A gnome with a love for magic and a talent for illusion. Her tricks and spells dazzle and delight, leaving audiences spellbound and wanting more.",
      ],
    },
  },
  "half-orc": {
    description:
      "Half-orcs are a rugged and imposing race, known for their strength, resilience, and fierce warrior spirit. They often face prejudice and discrimination due to their orcish heritage, but many half-orcs overcome these obstacles to become formidable adventurers, leaders, and champions of justice.",
    first_names: {
      male: [
        "Dorn",
        "Hakak",
        "Kronk",
        "Morg",
        "Rogar",
        "Thokk",
        "Ugarth",
        "Varg",
        "Zakar",
        "Balasar",
        "Dorn",
        "Grimmash",
        "Herg",
        "Krusk",
        "Rarg",
        "Shump",
        "Thar",
        "Ugarth",
        "Zark",
        "Drash",
      ],
      female: [
        "Baggi",
        "Luga",
        "Narla",
        "Ulfgar",
        "Vola",
        "Bulga",
        "Kara",
        "Maduk",
        "Shanku",
        "Tragga",
        "Baggi",
        "Dreda",
        "Grusha",
        "Holg",
        "Ruga",
        "Vola",
        "Zarr",
        "Bula",
        "Emen",
        "Ura",
      ],
    },
    last_names: [
      "Blackhand",
      "Bloodfist",
      "Darktide",
      "Dreadhelm",
      "Goreblade",
      "Ironhide",
      "Rageclaw",
      "Skullcrusher",
      "Stonebreaker",
      "Stormrage",
      "Thundershield",
      "Warmonger",
      "Blackhand",
      "Bloodfist",
      "Darktide",
      "Dreadhelm",
      "Goreblade",
      "Ironhide",
      "Rageclaw",
      "Skullcrusher",
    ],
    descriptions: {
      male: [
        "A half-orc with a muscular build and a stern expression. His scars tell the story of countless battles fought and won.",
        "A half-orc with a fierce glare and a menacing aura. His presence alone is often enough to intimidate his foes.",
        "A half-orc with a stoic demeanor and a quiet strength. His loyalty to his companions is unwavering, and his resolve is unbreakable.",
        "A half-orc with a wild mane of hair and a boisterous laugh. His love for revelry and good company is matched only by his thirst for adventure.",
        "A half-orc with a keen intellect and a strategic mind. His tactical prowess makes him a valuable asset on the battlefield.",
        "A half-orc with a gentle spirit and a kind heart. Despite his intimidating appearance, he is quick to offer aid to those in need.",
        "A half-orc with a scarred face and a haunted look in his eyes. His past is shrouded in mystery, but his determination to overcome his demons is clear.",
        "A half-orc with a fiery temper and a quick temper. His rage is a force to be reckoned with, and his enemies would do well to steer clear of his wrath.",
        "A half-orc with a grizzled appearance and a weary demeanor. His experiences have left their mark on him, but his spirit remains unbroken.",
        "A half-orc with a fierce determination and a relentless drive. His ambition knows no bounds, and he will stop at nothing to achieve his goals.",
        "A half-orc with a quick wit and a sharp tongue. His sarcasm and humor often mask his true feelings, but his loyalty to his friends is unwavering.",
        "A half-orc with a deep sense of honor and a strong moral compass. His code of ethics guides his actions, and he will always stand up for what is right.",
        "A half-orc with a gentle demeanor and a love for nature. His connection to the wilderness runs deep, and he feels most at home among the trees and the beasts that dwell within them.",
        "A half-orc with a love for music and a talent for playing instruments. His melodies are haunting and beautiful, reflecting the depths of his soul.",
        "A half-orc with a love for books and a thirst for knowledge. His studies have taken him to far-off lands and distant realms, but his thirst for knowledge remains unquenchable.",
        "A half-orc with a love for art and a talent for painting. His works are bold and vibrant, capturing the essence of the world around him.",
        "A half-orc with a love for food and a talent for cooking. His recipes are legendary, and his meals are the highlight of any gathering.",
        "A half-orc with a love for puzzles and a knack for solving them. His mind is like a finely tuned machine, always working to unravel the mysteries of the world.",
        "A half-orc with a love for magic and a talent for casting spells. His mastery of the arcane arts is awe-inspiring, and his spells are as potent as they are deadly.",
        "A half-orc with a love for the sea and a thirst for adventure. His tales of sailing the high seas and battling sea monsters are legendary.",
      ],
      female: [
        "A half-orc with a muscular build and a stern expression. Her scars tell the story of countless battles fought and won.",
        "A half-orc with a fierce glare and a menacing aura. Her presence alone is often enough to intimidate her foes.",
        "A half-orc with a stoic demeanor and a quiet strength. Her loyalty to her companions is unwavering, and her resolve is unbreakable.",
        "A half-orc with a wild mane of hair and a boisterous laugh. Her love for revelry and good company is matched only by her thirst for adventure.",
        "A half-orc with a keen intellect and a strategic mind. Her tactical prowess makes her a valuable asset on the battlefield.",
        "A half-orc with a gentle spirit and a kind heart. Despite her intimidating appearance, she is quick to offer aid to those in need.",
        "A half-orc with a scarred face and a haunted look in her eyes. Her past is shrouded in mystery, but her determination to overcome her demons is clear.",
        "A half-orc with a fiery temper and a quick temper. Her rage is a force to be reckoned with, and her enemies would do well to steer clear of her wrath.",
        "A half-orc with a grizzled appearance and a weary demeanor. Her experiences have left their mark on her, but her spirit remains unbroken.",
        "A half-orc with a fierce determination and a relentless drive. Her ambition knows no bounds, and she will stop at nothing to achieve her goals.",
        "A half-orc with a quick wit and a sharp tongue. Her sarcasm and humor often mask her true feelings, but her loyalty to her friends is unwavering.",
        "A half-orc with a deep sense of honor and a strong moral compass. Her code of ethics guides her actions, and she will always stand up for what is right.",
        "A half-orc with a gentle demeanor and a love for nature. Her connection to the wilderness runs deep, and she feels most at home among the trees and the beasts that dwell within them.",
        "A half-orc with a love for music and a talent for playing instruments. Her melodies are haunting and beautiful, reflecting the depths of her soul.",
        "A half-orc with a love for books and a thirst for knowledge. Her studies have taken her to far-off lands and distant realms, but her thirst for knowledge remains unquenchable.",
        "A half-orc with a love for art and a talent for painting. Her works are bold and vibrant, capturing the essence of the world around her.",
        "A half-orc with a love for food and a talent for cooking. Her recipes are legendary, and her meals are the highlight of any gathering.",
        "A half-orc with a love for puzzles and a knack for solving them. Her mind is like a finely tuned machine, always working to unravel the mysteries of the world.",
        "A half-orc with a love for magic and a talent for casting spells. Her mastery of the arcane arts is awe-inspiring, and her spells are as potent as they are deadly.",
        "A half-orc with a love for the sea and a thirst for adventure. Her tales of sailing the high seas and battling sea monsters are legendary.",
      ],
    },
  },
  tiefling: {
    description:
      "Tieflings are a race descended from fiends, with distinctive features such as horns, tails, and pointed teeth. Despite their infernal heritage, tieflings are not inherently evil and often struggle against the prejudices of others.",
    first_names: {
      male: [
        "Akmenos",
        "Amnon",
        "Barakas",
        "Damakos",
        "Ekemon",
        "Iados",
        "Kairon",
        "Leucis",
        "Melech",
        "Mordai",
        "Morthos",
        "Pelaios",
        "Skamos",
        "Therai",
        "Zeth",
        "Akmenos",
        "Amnon",
        "Barakas",
        "Damakos",
        "Ekemon",
      ],
      female: [
        "Akta",
        "Anakis",
        "Bryseis",
        "Criella",
        "Damaia",
        "Ea",
        "Kallista",
        "Lerissa",
        "Makaria",
        "Nemeia",
        "Orianna",
        "Phelaia",
        "Rieta",
        "Ulriech",
        "Zuriel",
        "Akta",
        "Anakis",
        "Bryseis",
        "Criella",
        "Damaia",
      ],
    },
    last_names: [
      "Darkhope",
      "Ironspur",
      "Nightbringer",
      "Ravenshadow",
      "Shadowborn",
      "Silverkin",
      "Skullborn",
      "Hollowborn",
      "Ravenshadow",
      "Shadowborn",
      "Silverkin",
      "Skullborn",
      "Hollowborn",
      "Loreweaver",
      "Nightrunner",
      "Dreadwalker",
      "Hellborn",
      "Nightrunner",
      "Dreadwalker",
      "Hellborn",
    ],
    descriptions: {
      male: [
        "A tiefling with deep red skin and glowing yellow eyes. His horns curve back from his temples, and his tail flicks restlessly behind him.",
        "A tiefling with dusky gray skin and piercing green eyes. His angular features are accentuated by his prominent fangs and pointed ears.",
        "A tiefling with midnight black skin and bright blue eyes. His devilish grin reveals rows of sharp teeth, and his pointed tail sways menacingly behind him.",
        "A tiefling with pale lavender skin and piercing violet eyes. His presence is unnerving, and his gaze seems to pierce straight into the soul.",
        "A tiefling with ashen gray skin and fiery orange eyes. His horns curl back from his forehead, and his tail lashes out in agitation.",
        "A tiefling with olive green skin and deep brown eyes. His features are sharp and angular, and his pointed tail twitches with anticipation.",
        "A tiefling with jet black skin and icy blue eyes. His movements are smooth and graceful, like those of a predator stalking its prey.",
        "A tiefling with bronze-colored skin and piercing silver eyes. His presence exudes confidence and authority, and his voice carries the weight of command.",
        "A tiefling with sallow yellow skin and glowing red eyes. His expression is unreadable, and his motives are shrouded in mystery.",
        "A tiefling with deep indigo skin and bright golden eyes. His horns are long and curved, and his tail lashes out with a mind of its own.",
        "A tiefling with dusky purple skin and piercing green eyes. His movements are fluid and graceful, like those of a dancer.",
        "A tiefling with pale blue skin and glowing green eyes. His features are delicate and refined, and his voice is soft but commanding.",
        "A tiefling with jet black skin and fiery red eyes. His presence is imposing, and his gaze is filled with a burning intensity.",
        "A tiefling with deep crimson skin and piercing yellow eyes. His horns are twisted and jagged, and his tail lashes out with a mind of its own.",
        "A tiefling with ashen gray skin and piercing violet eyes. His features are angular and severe, and his expression is one of perpetual disdain.",
        "A tiefling with dusky purple skin and glowing silver eyes. His presence is ethereal, and his movements are like those of a ghost drifting through the night.",
        "A tiefling with deep crimson skin and piercing green eyes. His horns are long and curved, and his tail flicks restlessly behind him.",
        "A tiefling with jet black skin and glowing orange eyes. His presence is unnerving, and his gaze seems to pierce straight into the soul.",
        "A tiefling with midnight blue skin and piercing red eyes. His features are sharp and angular, and his tail twitches with anticipation.",
        "A tiefling with dusky gray skin and piercing yellow eyes. His presence is imposing, and his voice carries the weight of command.",
      ],
      female: [
        "A tiefling with deep red skin and glowing yellow eyes. Her horns curve back from her temples, and her tail flicks restlessly behind her.",
        "A tiefling with dusky gray skin and piercing green eyes. Her angular features are accentuated by her prominent fangs and pointed ears.",
        "A tiefling with midnight black skin and bright blue eyes. Her devilish grin reveals rows of sharp teeth, and her pointed tail sways menacingly behind her.",
        "A tiefling with pale lavender skin and piercing violet eyes. Her presence is unnerving, and her gaze seems to pierce straight into the soul.",
        "A tiefling with ashen gray skin and fiery orange eyes. Her horns curl back from her forehead, and her tail lashes out in agitation.",
        "A tiefling with olive green skin and deep brown eyes. Her features are sharp and angular, and her pointed tail twitches with anticipation.",
        "A tiefling with jet black skin and icy blue eyes. Her movements are smooth and graceful, like those of a predator stalking its prey.",
        "A tiefling with bronze-colored skin and piercing silver eyes. Her presence exudes confidence and authority, and her voice carries the weight of command.",
        "A tiefling with sallow yellow skin and glowing red eyes. Her expression is unreadable, and her motives are shrouded in mystery.",
        "A tiefling with deep indigo skin and bright golden eyes. Her horns are long and curved, and her tail lashes out with a mind of its own.",
        "A tiefling with dusky purple skin and piercing green eyes. Her movements are fluid and graceful, like those of a dancer.",
        "A tiefling with pale blue skin and glowing green eyes. Her features are delicate and refined, and her voice is soft but commanding.",
        "A tiefling with jet black skin and fiery red eyes. Her presence is imposing, and her gaze is filled with a burning intensity.",
        "A tiefling with deep crimson skin and piercing yellow eyes. Her horns are twisted and jagged, and her tail lashes out with a mind of its own.",
        "A tiefling with ashen gray skin and piercing violet eyes. Her features are angular and severe, and her expression is one of perpetual disdain.",
        "A tiefling with dusky purple skin and glowing silver eyes. Her presence is ethereal, and her movements are like those of a ghost drifting through the night.",
        "A tiefling with deep crimson skin and piercing green eyes. Her horns are long and curved, and her tail flicks restlessly behind her.",
        "A tiefling with jet black skin and glowing orange eyes. Her presence is unnerving, and her gaze seems to pierce straight into the soul.",
        "A tiefling with midnight blue skin and piercing red eyes. Her features are sharp and angular, and her tail twitches with anticipation.",
        "A tiefling with dusky gray skin and piercing yellow eyes. Her presence is imposing, and her voice carries the weight of command.",
      ],
    },
  },
};
